[collector.prometheus]
  ip = "127.0.0.1"
  port = 9200

#[tester._defaults_]
#  interval = 120
#  timeout = 5

[[tester.true]]
  name = "always succeeds"

[[tester.false]]
  name = "always fails"

[[tester.sleep]]
  name = "nap time"
  sleep = 60
  timeout = 10
  interval = 2

[[tester.tcp]]
  # interval =
  # timeout =
  name = "printer"
  ip = "127.0.0.1"
  port = 631
  # banner =

[[tester.tcp]]
  # interval =
  # timeout =
  name = "no printer"
  ip = "127.0.0.1"
  port = 632
  # banner =

[[tester.tcp]]
  # interval =
  # timeout =
  name = "far away"
  ip = "66.111.4.4"
  port = 123
  # banner =

[[tester.tcp]]
  name = "vm ssh"
  ip = "10.211.55.49"
  port = 22
  banner = "^SSH-"

[[tester.http]]
  name = "printer web"
  url = "http://localhost:631"

[[tester.http]]
  name = "printer web 404"
  url = "http://localhost:631/zub"

[[tester.socket]]
  name = "mdns responder"
  path = "/var/run/mDNSResponder"

[[tester.socket]]
  name = "devnull is not a socket"
  path = "/dev/null"

[[tester.ping]]
  name = "ping local"
  ip = "127.0.0.1"

[[tester.ping]]
  name = "ping bad"
  ip = "126.0.0.1"

[[tester.tcp_tls]]
  name = "tls bad verify"
  ip = "127.0.0.1"
  port = 631

[[tester.tcp_tls]]
  name = "tls ok no verify"
  ip = "127.0.0.1"
  port = 631
  verify = 0

[[tester.tcp_tls]]
  name = "tls ok fingerprint"
  ip = "127.0.0.1"
  port = 631
  fingerprint = "sha256$c217a64e39887661e8fce082b39d475acee5fa096f106dd440b4bd72ff6ea28e"
