[collector.prometheus]
  class = "Hello::Collector::Prometheus"
  ip = "127.0.0.1"
  port = 9200

[group.servers]
  class = "Hello::Group::Static"

  [[group.servers.members]]
    id = "local"
    ip = "127.0.0.1"
  [[group.servers.members]]
    id = "local2"
    ip = "127.0.0.2"

  [group.servers.tester]
    ping = {
      class = "Hello::Tester::Ping"
    }

[tester."static ping"]
  class = "Hello::Tester::Ping"
  ip = "127.0.0.1"
  interval = 5
